---
title: "Merge SRA Data"
author: "Victoria Flanary"
date: "2025-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objective
- Merge SRR Accession Lists for untreated neuroblastoma cell line and hNCC
ATAC-seq data from GEO (GSE138293 and GSE108517). 
- Merge the SRA Run Tables for each of the above GEO accessions to generate
a comprehensive metadata dataframe.

# Set-up
```{r load packages}
library(tidyverse)
library(rstudioapi)
library(here)
library(styler)
library(lintr)
```

# SRR Accession Lists
```{r read in the srr acc lists}
nb_lines <- readLines(
  here("Untreated_ATAC", "docs", "GSE138293_SRR_Acc_List.txt")
)

hnccs <- readLines(
  here("Untreated_ATAC", "docs", "GSE108517_SRR_Acc_List.txt")
)
```

```{r concatenate the accession lists}
merged_srr_acc <- c(nb_lines, hnccs)
```

```{r save the merged list}
write.table(
  merged_srr_acc,
  here("Untreated_ATAC", "docs", "merged_srr_acc_list.txt"),
  sep = "\t",
  row.names = FALSE,
  col.names = FALSE,
  quote = FALSE
)
```

# End of script
```{r style code}
script <- rstudioapi::getSourceEditorContext()$path
style_file(script)
lint(script)
```

```{r clean environment}
rm(list = ls())
gc()
```
